import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Girls Shop",
  description: "Generated by Md Abdul Kyum",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="girlsShopLight">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        <main className="h-screen">
            {children}
        </main>

      </body>
    </html>
  );
}
